# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="ім'я")),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'verbose_name': 'Мiсто',
                'verbose_name_plural': 'Мiста',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="ім'я")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='avatar')),
                ('short_name', models.CharField(max_length=50, verbose_name='short_name')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_registered')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created')),
                ('address', models.CharField(max_length=500, verbose_name='address')),
                ('facebook', models.CharField(blank=True, max_length=500, null=True, verbose_name='facebook')),
                ('twitter', models.CharField(blank=True, max_length=500, null=True, verbose_name='twitter')),
                ('instagram', models.CharField(blank=True, max_length=500, null=True, verbose_name='instagram')),
                ('website', models.CharField(blank=True, max_length=500, null=True, verbose_name='website')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.City')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клуби',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='avatar')),
                ('name', models.CharField(max_length=100, verbose_name="ім'я")),
                ('surname', models.CharField(max_length=100, verbose_name='surname')),
                ('birth_date', models.DateField(verbose_name='birth_date')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('licence_number', models.CharField(max_length=50, verbose_name='licence_number')),
                ('gender', models.CharField(choices=[('M', 'Чоловiк'), ('F', 'Жiнка')], max_length=1, verbose_name='gender')),
                ('facebook', models.CharField(blank=True, max_length=500, null=True, verbose_name='facebook')),
                ('twitter', models.CharField(blank=True, max_length=500, null=True, verbose_name='twitter')),
                ('instagram', models.CharField(blank=True, max_length=500, null=True, verbose_name='instagram')),
                ('website', models.CharField(blank=True, max_length=500, null=True, verbose_name='website')),
                ('local_tournament_points', models.FloatField(default=0, verbose_name='local_tournament_points')),
                ('foreign_tournament_points', models.FloatField(default=0, verbose_name='foreign_tournament_points')),
                ('b_tournament_points', models.FloatField(default=0, verbose_name='b_tournament_points')),
                ('current_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='federation.Club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Гравець',
                'verbose_name_plural': 'Гравці',
            },
        ),
        migrations.AddField(
            model_name='club',
            name='president',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.Player'),
        ),
    ]
