# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import federation.storage


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=federation.storage.OverwriteStorage(), upload_to='', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=federation.storage.OverwriteStorage(), upload_to='', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
