# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0002_auto_20170728_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTeamMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_capitan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='name')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команди',
            },
        ),
        migrations.AlterField(
            model_name='player',
            name='licence_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='licence_number'),
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(through='federation.PlayerTeamMembership', to='federation.Player'),
        ),
        migrations.AddField(
            model_name='playerteammembership',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.Player'),
        ),
        migrations.AddField(
            model_name='playerteammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.Team'),
        ),
    ]
