# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import federation.storage


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0003_auto_20170811_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbiterTournamentMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_arbiter', models.BooleanField(default=False, verbose_name='Головний арбітр')),
                ('arbiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.Player', verbose_name='Арбітр')),
            ],
            options={
                'verbose_name': 'Арбітри турніру',
                'verbose_name_plural': 'Арбітри турніру',
            },
        ),
        migrations.CreateModel(
            name='TeamTournamentMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_min', models.IntegerField(default=0, verbose_name='Місце')),
                ('place_max', models.IntegerField(default=0, verbose_name='Місце (максимальне)')),
                ('date_registration', models.DateField(default=django.utils.timezone.now, verbose_name='Дата реєстрації')),
                ('rating_points', models.IntegerField(default=0, verbose_name='Рейтингові пункти за турнір')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.Team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Команди турніру',
                'verbose_name_plural': 'Команди турніру',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('category', models.CharField(choices=[('open', 'Вiдктитий'), ('fpu', 'ФПУ'), ('away', 'Закордонний')], max_length=5, verbose_name='Категорія')),
                ('is_b_tournament', models.BooleanField(default=False, verbose_name='Турнір "B"')),
                ('is_goes_to_rating', models.BooleanField(default=False, verbose_name='Рейтинговий')),
                ('rating_coefficient', models.FloatField(default=1, verbose_name='Рейтинговий коефіцієнт')),
                ('place', models.CharField(max_length=500, verbose_name='Місце проведення')),
                ('date_start', models.TimeField(default=django.utils.timezone.now, verbose_name='Час початку')),
                ('date_registration_stop', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата закінчення реєстрації')),
                ('number_of_players_in_team_min', models.IntegerField(default=1, verbose_name='Мінімальна кількість гравців в команді')),
                ('number_of_players_in_team_max', models.IntegerField(default=1, verbose_name='Кількість гравців в команді (з запасними)')),
                ('format', models.CharField(choices=[('swiss', 'Швейцарська система'), ('swissko', 'Швейцарська система + На виліт'), ('ko', 'На виліт'), ('each', 'Кожен з кожним')], max_length=5, verbose_name='Формат')),
                ('terms', models.FileField(blank=True, null=True, storage=federation.storage.AvatarsStorage(), upload_to='', verbose_name='Регламент')),
                ('teams_limit', models.IntegerField(default=100, verbose_name='Ліміт команд')),
                ('fee', models.TextField(blank=True, null=True, verbose_name='Внески')),
                ('arbiters', models.ManyToManyField(related_name='tournament_arbiters', through='federation.ArbiterTournamentMembership', to='federation.Player')),
                ('federation_delegat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_federation_delegat', to='federation.Player', verbose_name='Делегат федерації')),
                ('organizer_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='federation.Club', verbose_name='Клуб організатор')),
                ('teams', models.ManyToManyField(through='federation.TeamTournamentMembership', to='federation.Team')),
            ],
            options={
                'verbose_name': 'Турнір',
                'verbose_name_plural': 'Турніри',
            },
        ),
        migrations.AlterModelOptions(
            name='playerteammembership',
            options={'verbose_name': 'Належнiсть до команд', 'verbose_name_plural': 'Належнiсть до команд'},
        ),
        migrations.AlterField(
            model_name='playerteammembership',
            name='is_capitan',
            field=models.BooleanField(default=False, verbose_name='Капiтан'),
        ),
        migrations.AlterField(
            model_name='playerteammembership',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.Player', verbose_name='Гравцi'),
        ),
        migrations.AlterField(
            model_name='playerteammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.Team', verbose_name='Команди'),
        ),
        migrations.AddField(
            model_name='teamtournamentmembership',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.Tournament', verbose_name='Турнір'),
        ),
        migrations.AddField(
            model_name='arbitertournamentmembership',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.Tournament', verbose_name='Турнір'),
        ),
    ]
