# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0004_auto_20170814_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='date_start',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата початку'),
        ),
    ]
