# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0005_auto_20170814_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Нотатки'),
        ),
    ]
