# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0006_tournament_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('swiss', 'Швейцарська система'), ('swiko', 'Швейцарська система + На виліт'), ('ko', 'На виліт'), ('each', 'Кожен з кожним')], max_length=5, verbose_name='Формат'),
        ),
    ]
