# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0007_auto_20170814_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='arbiter_level',
            field=models.CharField(blank=True, choices=[('club', 'Клубний'), ('regional', 'Регіональний'), ('national', 'Національний'), ('euro', 'Європейський'), ('fipjp', 'Міжнародний')], max_length=10, null=True, verbose_name='Рівень арбітражу'),
        ),
    ]