# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0008_player_arbiter_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='club',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.City', verbose_name='Мiсто'),
        ),
        migrations.AlterField(
            model_name='club',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='club',
            name='date_registered',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Повна назва'),
        ),
        migrations.AlterField(
            model_name='club',
            name='president',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.Player', verbose_name='Президент'),
        ),
        migrations.AlterField(
            model_name='club',
            name='short_name',
            field=models.CharField(max_length=50, verbose_name='Коротка назва'),
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateField(verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='player',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='federation.Club', verbose_name='Клуб'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('M', 'Чоловiк'), ('F', 'Жiнка')], max_length=1, verbose_name='Стать'),
        ),
        migrations.AlterField(
            model_name='player',
            name='licence_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер ліцензії'),
        ),
        migrations.AlterField(
            model_name='player',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Прізвищє'),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(through='federation.PlayerTeamMembership', to='federation.Player', verbose_name='Гравці'),
        ),
    ]
