# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0009_auto_20170816_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_in_national_team_elimination',
            field=models.BooleanField(default=False, verbose_name='Чи є в основному складі збірної України?'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_in_national_team_selection',
            field=models.BooleanField(default=False, verbose_name='Чи є в збірній України?'),
        ),
        migrations.AddField(
            model_name='player',
            name='position_in_selection',
            field=models.CharField(blank=True, choices=[('point', 'Поінтер'), ('middle', 'Мідл'), ('shooter', 'Шутер')], max_length=10, null=True, verbose_name='Позиція в збірній'),
        ),
        migrations.AddField(
            model_name='player',
            name='prefred_position',
            field=models.CharField(blank=True, choices=[('point', 'Поінтер'), ('middle', 'Мідл'), ('shooter', 'Шутер')], max_length=10, null=True, verbose_name='Позиція'),
        ),
    ]
