# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0011_auto_20170816_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='National_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Повна назва команди')),
            ],
            options={
                'verbose_name': 'Збірна команди',
                'verbose_name_plural': 'Збірнi команди',
            },
        ),
        migrations.CreateModel(
            name='PlayerNational_teamMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('player', 'Гравець'), ('coach', 'Тренер'), ('main_coach', 'Головний тренер'), ('capitan', 'Капітан')], max_length=50, verbose_name='Позиція')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.Player', verbose_name='Гравцi')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.National_team', verbose_name='Команди')),
            ],
            options={
                'verbose_name': 'Належнiсть до команд',
                'verbose_name_plural': 'Належнiсть до команд',
            },
        ),
        migrations.AddField(
            model_name='national_team',
            name='players',
            field=models.ManyToManyField(through='federation.PlayerNational_teamMembership', to='federation.Player', verbose_name='Гравці'),
        ),
    ]
