# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0012_auto_20170816_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playernational_teammembership',
            name='position',
            field=models.CharField(choices=[('player', 'Гравець'), ('coach', 'Тренер'), ('main_coach', 'Головний тренер'), ('capitan', 'Капітан'), ('selection', 'Основний склад')], max_length=50, verbose_name='Позиція'),
        ),
    ]