# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0013_auto_20170816_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='b_tournament_points',
        ),
        migrations.RemoveField(
            model_name='player',
            name='foreign_tournament_points',
        ),
        migrations.RemoveField(
            model_name='player',
            name='local_tournament_points',
        ),
    ]
