# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0014_auto_20170824_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_processing_finished',
            field=models.BooleanField(default=False, verbose_name='Результати турніру опрацьовано'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.CharField(choices=[('open', 'Вiдктитий'), ('fpu', 'ФПУ'), ('away', 'Закордонний'), ('other', 'Інше')], max_length=5, verbose_name='Категорія'),
        ),
    ]
