# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0016_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_processed_by_system',
            field=models.BooleanField(default=False, verbose_name='Оправцьовано системою (рейтингові бали нараховано)'),
        ),
    ]
