# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0017_tournament_is_processed_by_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='arbiters',
            field=models.ManyToManyField(blank=True, related_name='tournament_arbiters', through='federation.ArbiterTournamentMembership', to='federation.Player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='tournament_teams', through='federation.TeamTournamentMembership', to='federation.Team'),
        ),
    ]
