# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0018_auto_20170928_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('swiss', 'Швейцарська система'), ('swiko', 'Швейцарська система + На виліт'), ('ko', 'На виліт'), ('each', 'Кожен з кожним'), ('mele', 'Супер-меле')], max_length=5, verbose_name='Формат'),
        ),
    ]
