# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0019_auto_20170928_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='total_number_of_teams',
            field=models.IntegerField(blank=True, null=True, verbose_name='Повна кількість команд'),
        ),
    ]
