# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '020_tournament_total_number_of_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='is_processed_by_system',
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_ukrainian_league',
            field=models.BooleanField(default=False, verbose_name='Турнір Української Ліги Петанку'),
        ),
    ]