# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0021_auto_20180106_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закінчення'),
        ),
    ]