# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0022_tournament_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='rating_coefficient',
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_power',
            field=models.FloatField(default=1, verbose_name='Сила турніру'),
        ),
    ]