# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0023_auto_20180120_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='tournament_power',
            new_name='power',
        ),
        migrations.AddField(
            model_name='player',
            name='current_rating',
            field=models.IntegerField(default=0, verbose_name='Поточні рейтингові пункти'),
        ),
        migrations.AddField(
            model_name='teamtournamentmembership',
            name='power',
            field=models.IntegerField(default=0, verbose_name='Сила команди'),
        ),
    ]
