# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0024_auto_20180120_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='rating_coefficient',
            field=models.FloatField(default=1, verbose_name='Рейтинговий коефіцієнт'),
        ),
    ]
