# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0025_tournament_rating_coefficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.CharField(choices=[('open', 'Вiдкритий'), ('fpu', 'ФПУ'), ('away', 'Закордонний'), ('other', 'Інше')], max_length=5, verbose_name='Категорія'),
        ),
    ]