# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0026_auto_20180120_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_ready_for_processing',
            field=models.BooleanField(default=False, verbose_name='Турнір готовий до опрацювання'),
        ),
    ]
