# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0027_tournament_is_ready_for_processing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='power',
            field=models.FloatField(default=0, verbose_name='Сила турніру'),
        ),
    ]