# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0028_auto_20180121_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtournamentmembership',
            name='rating_points',
            field=models.FloatField(default=0, verbose_name='Рейтингові пункти за турнір'),
        ),
    ]