# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0029_auto_20180121_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_rating_b',
            field=models.IntegerField(default=0, verbose_name='Поточні рейтингові пункти у турнірах "B'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_rating_liga',
            field=models.IntegerField(default=0, verbose_name='Поточні рейтингові пункти у турнірах "Ліги"'),
        ),
    ]
