# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0031_team_admin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='admin_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Назва в адмiн панелi'),
        ),
    ]
