# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0032_auto_20180206_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='admin_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Назва в адмiн панелi'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='name'),
        ),
    ]
