# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0033_auto_20180206_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_rating',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Поточні рейтингові пункти'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_rating_b',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Поточні рейтингові пункти у турнірах "B'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_rating_liga',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Поточні рейтингові пункти у турнірах "Ліги"'),
        ),
        migrations.AlterField(
            model_name='teamtournamentmembership',
            name='rating_points',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Рейтингові пункти за турнір'),
        ),
    ]