# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0034_auto_20180206_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtournamentmembership',
            name='power',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Сила команди'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='power',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Сила турніру'),
        ),
    ]