# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import federation.storage


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0035_auto_20180206_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=federation.storage.MediaStorage(), upload_to='', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=federation.storage.MediaStorage(), upload_to='', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='terms',
            field=models.FileField(blank=True, null=True, storage=federation.storage.MediaStorage(), upload_to='', verbose_name='Регламент'),
        ),
    ]