# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import federation.storage


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0036_auto_20180206_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Нотатки')),
                ('file', models.FileField(blank=True, null=True, storage=federation.storage.MediaStorage(), upload_to='', verbose_name='Файл')),
                ('category', models.CharField(choices=[('rules', 'Правила'), ('regulations', 'Регламентні документи'), ('tournament_regulations', 'Регламенти турнірів'), ('for_print', 'Документи до друку'), ('other', 'Інше')], max_length=100, verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
            },
        ),
    ]
