# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import federation.storage


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0037_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=federation.storage.MediaStorage(), upload_to='', verbose_name='Файл'),
        ),
    ]