# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0038_auto_20180208_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('rules', 'Правила'), ('regulations', 'Регламентні документи'), ('tournament_regulations', 'Регламенти турнірів'), ('for_print', 'Документи до друку'), ('oficial', 'Свідоцтва та офіційні документи'), ('other', 'Інше')], max_length=100, verbose_name='Категорія'),
        ),
    ]