# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0039_auto_20180208_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, verbose_name='Рік')),
                ('rating', models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Рейтингові пункти')),
                ('rating_b', models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Рейтингові пункти у турнірах "B')),
                ('rating_liga', models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Рейтингові пункти у турнірах "Ліги"')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='federation.Club', verbose_name='Клуб')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.Player', verbose_name='Гравець')),
            ],
            options={
                'verbose_name': 'Сезони',
                'verbose_name_plural': 'Сезони',
            },
        ),
    ]