# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0040_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='coach_level',
            field=models.CharField(blank=True, choices=[('second', 'Перша категорія'), ('first', 'Друга категорія'), ('highest', 'Вища категорія')], max_length=20, null=True, verbose_name='Тренерська категорія'),
        ),
    ]