# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0042_auto_20180217_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='arbiter_level',
            field=models.CharField(blank=True, choices=[('club', 'Друга категорія'), ('regional', 'Перша категорія'), ('national', 'Національний'), ('euro', 'Арбітр CEP (Європейський)'), ('fipjp', 'Арбітр FIPJP (Міжнародний)')], max_length=10, null=True, verbose_name='Рівень арбітражу'),
        ),
    ]