# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0043_auto_20180224_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date_registration_stop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закінчення реєстрації'),
        ),
    ]
