# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0044_auto_20180402_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('swiss', 'Швейцарська система'), ('swiko', 'Швейцарська система + На виліт'), ('ko', 'На виліт'), ('each', 'Кожен з кожним'), ('tir', 'Турнір з тиру'), ('mele', 'Супер-меле')], max_length=5, verbose_name='Формат'),
        ),
    ]