# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0045_auto_20180409_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='coach_level',
            field=models.CharField(blank=True, choices=[('A', 'A (Аніматор)'), ('I1', 'I1 (Інструктор 1-ої категорії)'), ('I2', 'I2 (Інструктор 2-ої категорії)'), ('I3', 'I3 (Інструктор 3-ої категорії)'), ('I4', 'I4 (Інструктор 4-ої категорії)'), ('E1', 'E1 (Тренер-інструктор 1-ої категорії)'), ('E2', 'E2 (Тренер-інструктор 2-ої категорії)'), ('E3', 'E3 (Тренер-інструктор 3-ої категорії)'), ('E4', 'E4 (Тренер-інструктор 4-ої категорії)')], max_length=20, null=True, verbose_name='Тренерська категорія'),
        ),
    ]