# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0046_auto_20180420_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_power',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Поточна сила'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_power_b',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Поточна сила у турнірах "B'),
        ),
        migrations.AddField(
            model_name='teamtournamentmembership',
            name='rating_power',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Рейтингова сила за турнір'),
        ),
    ]
