# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-27 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0047_auto_20180508_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Назва')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок у меню')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Нотатки')),
            ],
            options={
                'verbose_name': 'Підрозділ ФПУ',
                'verbose_name_plural': 'Підрозділи ФПУ',
            },
        ),
        migrations.CreateModel(
            name='PlayerDepartmentMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=1000, verbose_name='Роль')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.Player', verbose_name='Гравцi')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.Department', verbose_name='Підрозділи ФПУ')),
            ],
            options={
                'verbose_name': 'Належнiсть до підрозділу',
                'verbose_name_plural': 'Належнiсть до підрозділу',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='players',
            field=models.ManyToManyField(through='federation.PlayerDepartmentMembership', to='federation.Player', verbose_name='Гравці'),
        ),
    ]
