# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0048_auto_20181127_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_licence_active',
            field=models.BooleanField(default=False, verbose_name='Ліцензія активна'),
        ),
    ]
