# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 21:23
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0049_player_is_licence_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Країна'),
        ),
    ]
