# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-05 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0050_tournament_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='main_organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_main_organizer', to='federation.Player', verbose_name='Головний організатор'),
        ),
    ]
