# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-05 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0051_tournament_main_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='final_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Нотатки для підсумкового протоколу'),
        ),
    ]
