# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0052_tournament_final_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_rating_b_tournaments',
            field=models.TextField(blank=True, null=True, verbose_name='Турніри що впливають на поточний рейтинг у турнірах B'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_rating_tournaments',
            field=models.TextField(blank=True, null=True, verbose_name='Турніри що впливають на поточний рейтинг'),
        ),
    ]
