# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-23 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0053_auto_20190506_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_power_inclusive',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Поточна сила у інклюзивних турнірах'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_rating_inclusive',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Поточні рейтингові пункти в інклюзивних турнірах'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_rating_inclusive_tournaments',
            field=models.TextField(blank=True, null=True, verbose_name='Турніри що впливають на поточний рейтинг у інклюзивних турнірах'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_inclusive',
            field=models.BooleanField(default=False, verbose_name='Інклюзивний гравець'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_inclusive',
            field=models.BooleanField(default=False, verbose_name='Інклюзивний турнір'),
        ),
    ]