# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0054_auto_20190623_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступний'),
        ),
    ]