# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-23 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0056_auto_20200721_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('fpu', 'Свідоцтва та установчі документи ФПУ'), ('tournaments', 'Положення та правила проведення змагань'), ('international', 'Документи CEP, FIPJP, CMSB'), ('forms', 'Форми документів для організаторів змагань та спортсменів'), ('rules', 'Правила'), ('regulations', 'Регламентні документи'), ('tournament_regulations', 'Регламенти турнірів'), ('for_print', 'Документи до друку'), ('official', 'Свідоцтва та офіційні документи'), ('other', 'Інше')], max_length=100, verbose_name='Категорія'),
        ),
    ]

    