# Generated by Django 5.1.6 on 2025-02-20 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0058_tournament_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitertournamentmembership',
            name='arbiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='federation.player', verbose_name='Арбітр'),
        ),
        migrations.AlterField(
            model_name='arbitertournamentmembership',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='federation.tournament', verbose_name='Турнір'),
        ),
        migrations.AlterField(
            model_name='club',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='federation.city', verbose_name='Мiсто'),
        ),
        migrations.AlterField(
            model_name='club',
            name='president',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='federation.player', verbose_name='Президент'),
        ),
        migrations.AlterField(
            model_name='playerdepartmentmembership',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='federation.player', verbose_name='Гравцi'),
        ),
        migrations.AlterField(
            model_name='playerdepartmentmembership',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='federation.department', verbose_name='Підрозділи ФПУ'),
        ),
        migrations.AlterField(
            model_name='playernational_teammembership',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='federation.player', verbose_name='Гравцi'),
        ),
        migrations.AlterField(
            model_name='playernational_teammembership',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='federation.national_team', verbose_name='Команди'),
        ),
        migrations.AlterField(
            model_name='playerteammembership',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='federation.player', verbose_name='Гравцi'),
        ),
        migrations.AlterField(
            model_name='playerteammembership',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='federation.team', verbose_name='Команди'),
        ),
        migrations.AlterField(
            model_name='season',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='federation.player', verbose_name='Гравець'),
        ),
        migrations.AlterField(
            model_name='teamtournamentmembership',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='federation.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='teamtournamentmembership',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='federation.tournament', verbose_name='Турнір'),
        ),
    ]
    