# Generated by Django 5.1.6 on 2025-02-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0059_alter_arbitertournamentmembership_arbiter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdepartmentmembership',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
    ]
    