# Generated by Django 5.1.6 on 2025-02-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0060_playerdepartmentmembership_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdepartmentmembership',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок на сторінці'),
        ),
    ]
  