# Generated by Django 5.1.6 on 2025-02-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0061_playerdepartmentmembership_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
    ]
    