# Generated by Django 5.1.6 on 2025-02-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0062_record_date_created_alter_record_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Значення'),
        ),
    ]
    