# Generated by Django 5.1.6 on 2025-03-03 13:29

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0063_record_notes_alter_record_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='По батькові'),
        ),
        migrations.AddField(
            model_name='player',
            name='sport_title',
            field=models.CharField(blank=True, choices=[('candidate', 'Кандидат у майстри спорту України'), ('master', 'Майстер спорту України'), ('master_sport', 'Майстер спорту міжнародного класу'), ('honored_master_sport', 'Заслужений майстер спорту України')], max_length=100, null=True, verbose_name='Спортивне звання'),
        ),
        migrations.AlterField(
            model_name='player',
            name='arbiter_level',
            field=models.CharField(blank=True, choices=[('junior', 'Юний спортивний арбітр'), ('arbiter', 'Арбітр Федерації петанку України'), ('club', 'Спортивний арбітр II-ої категорії'), ('regional', 'Спортивний арбітр I-ої категорії'), ('national', 'Спортивний арбітр національної категорії'), ('euro', 'Арбітр CEP (Європейська категорія)'), ('fipjp', 'Арбітр FIPJP (Світова категорія)')], max_length=10, null=True, verbose_name='Рівень арбітражу'),
        ),
        migrations.AlterField(
            model_name='player',
            name='country',
            field=django_countries.fields.CountryField(default='UA', max_length=2, verbose_name='Країна'),
        ),
    ]
  