# Generated by Django 5.1.6 on 2025-03-03 13:32

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0064_player_second_name_player_sport_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='UA', max_length=2, null=True, verbose_name='Країна'),
        ),
    ]
  