# Generated by Django 5.1.6 on 2025-08-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0065_alter_tournament_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('fpu', 'Свідоцтва та установчі документи ФПУ'), ('tournaments', 'Положення та правила проведення змагань'), ('international', 'Документи CEP, FIPJP, CMSB'), ('forms', 'Форми документів для організаторів змагань та спортсменів'), ('rules', 'Правила'), ('regulations', 'Регламентні документи'), ('tournament_regulations', 'Регламенти турнірів'), ('for_print', 'Документи до друку'), ('official', 'Свідоцтва та офіційні документи'), ('umpire_department', 'Документи суддівського комітету ФПУ'), ('other', 'Інше')], max_length=100, verbose_name='Категорія'),
        ),
    ]