# Generated by Django migration
# -*- coding: utf-8 -*-

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0066_alter_document_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Унікальний код категорії (наприклад: fpu, tournaments)', max_length=100, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('order', models.IntegerField(default=0, help_text='Порядок відображення в списку', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категорія документів',
                'verbose_name_plural': 'Категорії документів',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='federation.documentcategory', verbose_name='Категорія'),
        ),
    ]
