# Generated by Django migration
# -*- coding: utf-8 -*-

from django.db import migrations, models
import django.db.models.deletion


def populate_categories(apps, schema_editor):
    DocumentCategory = apps.get_model('federation', 'DocumentCategory')
    Document = apps.get_model('federation', 'Document')
    
    # Define the categories in order
    categories_data = [
        ('fpu', 'Свідоцтва та установчі документи ФПУ', 0),
        ('tournaments', 'Положення та правила проведення змагань', 1),
        ('international', 'Документи CEP, FIPJP, CMSB', 2),
        ('forms', 'Форми документів для організаторів змагань та спортсменів', 3),
        ('rules', 'Правила', 4),
        ('regulations', 'Регламентні документи', 5),
        ('tournament_regulations', 'Регламенти турнірів', 6),
        ('for_print', 'Документи до друку', 7),
        ('official', 'Свідоцтва та офіційні документи', 8),
        ('umpire_department', 'Документи суддівського комітету ФПУ', 9),
        ('other', 'Інше', 10),
    ]
    
    # Create categories
    category_map = {}
    for code, name, order in categories_data:
        category, created = DocumentCategory.objects.get_or_create(
            code=code,
            defaults={'name': name, 'order': order, 'is_active': True}
        )
        category_map[code] = category
    
    # Migrate existing documents
    for document in Document.objects.all():
        if document.category and document.category in category_map:
            document.category_new = category_map[document.category]
            document.save()
        elif not document.category_new:
            # If no category, assign 'other' as default
            document.category_new = category_map.get('other')
            if document.category_new:
                document.save()


def reverse_populate_categories(apps, schema_editor):
    Document = apps.get_model('federation', 'Document')
    DocumentCategory = apps.get_model('federation', 'DocumentCategory')
    
    # Set category back to the code value
    for document in Document.objects.all():
        if document.category_new:
            document.category = document.category_new.code
            document.save()
    
    # Delete categories
    DocumentCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0067_create_document_category'),
    ]

    operations = [
        migrations.RunPython(populate_categories, reverse_populate_categories),
        migrations.AlterField(
            model_name='document',
            name='category_new',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='federation.documentcategory', verbose_name='Категорія'),
        ),
    ]
