# Generated by Django migration
# -*- coding: utf-8 -*-

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0069_migrate_document_category_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email адреса')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Підтверджено')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата підтвердження')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_confirmation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Підтвердження email',
                'verbose_name_plural': 'Підтвердження email',
            },
        ),
    ]
