# Generated by Django 5.1.6 on 2026-05-20 22:05

import django.db.models.deletion
import django.utils.timezone
import federation.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0070_email_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitertournamentmembership',
            name='is_main_arbiter',
            field=models.BooleanField(default=False, verbose_name='Head arbiter'),
        ),
        migrations.AlterField(
            model_name='club',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='club',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='club',
            name='date_registered',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='club',
            name='short_name',
            field=models.CharField(max_length=50, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='department',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Menu order'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='federation.documentcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=federation.storage.MediaStorage(), upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='code',
            field=models.CharField(help_text='Unique category code (for example: fpu, tournaments)', max_length=100, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order in the list', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmed'),
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmation date'),
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='national_team',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Full team name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='arbiter_level',
            field=models.CharField(blank=True, choices=[('junior', 'Junior sports arbiter'), ('arbiter', 'Ukrainian Petanque Federation arbiter'), ('club', 'Sports arbiter, category II'), ('regional', 'Sports arbiter, category I'), ('national', 'National category sports arbiter'), ('euro', 'CEP arbiter (European category)'), ('fipjp', 'FIPJP arbiter (world category)')], max_length=10, null=True, verbose_name='Arbitration level'),
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateField(verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='player',
            name='coach_level',
            field=models.CharField(blank=True, choices=[('A', 'A (Animator)'), ('I1', 'I1 (Instructor, category 1)'), ('I2', 'I2 (Instructor, category 2)'), ('I3', 'I3 (Instructor, category 3)'), ('I4', 'I4 (Instructor, category 4)'), ('E1', 'E1 (Coach-instructor, category 1)'), ('E2', 'E2 (Coach-instructor, category 2)'), ('E3', 'E3 (Coach-instructor, category 3)'), ('E4', 'E4 (Coach-instructor, category 4)')], max_length=20, null=True, verbose_name='Coach category'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_power',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Current power'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_power_b',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Current power in B tournaments'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_power_inclusive',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Current power in inclusive tournaments'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_rating',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Current rating points'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_rating_b',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Current rating points in B tournaments'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_rating_b_tournaments',
            field=models.TextField(blank=True, null=True, verbose_name='Tournaments affecting current rating in B tournaments'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_rating_inclusive',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Current rating points in inclusive tournaments'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_rating_inclusive_tournaments',
            field=models.TextField(blank=True, null=True, verbose_name='Tournaments affecting current rating in inclusive tournaments'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_rating_liga',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Current rating points in League tournaments'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_rating_tournaments',
            field=models.TextField(blank=True, null=True, verbose_name='Tournaments affecting current rating'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('F', 'Woman')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_inclusive',
            field=models.BooleanField(default=False, verbose_name='Inclusive player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_licence_active',
            field=models.BooleanField(default=False, verbose_name='License active'),
        ),
        migrations.AlterField(
            model_name='player',
            name='licence_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='License number'),
        ),
        migrations.AlterField(
            model_name='player',
            name='prefred_position',
            field=models.CharField(blank=True, choices=[('point', 'Pointer'), ('middle', 'Middle'), ('shooter', 'Shooter')], max_length=10, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='player',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='sport_title',
            field=models.CharField(blank=True, choices=[('candidate', 'Candidate Master of Sports of Ukraine'), ('master', 'Master of Sports of Ukraine'), ('master_sport', 'International Class Master of Sports'), ('honored_master_sport', 'Honored Master of Sports of Ukraine')], max_length=100, null=True, verbose_name='Sports title'),
        ),
        migrations.AlterField(
            model_name='player',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='playerdepartmentmembership',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='playerdepartmentmembership',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Page order'),
        ),
        migrations.AlterField(
            model_name='playerdepartmentmembership',
            name='role',
            field=models.CharField(max_length=1000, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='playernational_teammembership',
            name='position',
            field=models.CharField(choices=[('player', 'Player'), ('coach', 'Coach'), ('main_coach', 'Head coach'), ('capitan', 'Captain'), ('selection', 'Main squad')], max_length=50, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='playerteammembership',
            name='is_capitan',
            field=models.BooleanField(default=False, verbose_name='Captain'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='record',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='season',
            name='rating',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Rating points'),
        ),
        migrations.AlterField(
            model_name='season',
            name='rating_b',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Rating points in B tournaments'),
        ),
        migrations.AlterField(
            model_name='season',
            name='rating_liga',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Rating points in League tournaments'),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(default=0, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='teamtournamentmembership',
            name='date_registration',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='teamtournamentmembership',
            name='place_max',
            field=models.IntegerField(default=0, verbose_name='Place (maximum)'),
        ),
        migrations.AlterField(
            model_name='teamtournamentmembership',
            name='place_min',
            field=models.IntegerField(default=0, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='teamtournamentmembership',
            name='power',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Team power'),
        ),
        migrations.AlterField(
            model_name='teamtournamentmembership',
            name='rating_points',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Rating points for tournament'),
        ),
        migrations.AlterField(
            model_name='teamtournamentmembership',
            name='rating_power',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Rating power for tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.CharField(choices=[('open', 'Open'), ('fpu', 'UPF'), ('away', 'International tournament'), ('other', 'Other')], max_length=5, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date_registration_stop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Registration deadline'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='fee',
            field=models.TextField(blank=True, null=True, verbose_name='Fees'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='final_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes for the final protocol'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('swiss', 'Swiss system'), ('swiko', 'Swiss system + Knockout'), ('ko', 'Knockout'), ('each', 'Round robin'), ('tir', 'Shooting tournament'), ('mele', 'Super melee')], max_length=5, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_b_tournament',
            field=models.BooleanField(default=False, verbose_name='B tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_goes_to_rating',
            field=models.BooleanField(default=False, verbose_name='Rating tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_inclusive',
            field=models.BooleanField(default=False, verbose_name='Inclusive tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_processing_finished',
            field=models.BooleanField(default=False, verbose_name='Tournament results processed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_ready_for_processing',
            field=models.BooleanField(default=False, verbose_name='Tournament is ready for processing'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_ukrainian_league',
            field=models.BooleanField(default=False, verbose_name='Ukrainian Petanque League tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='meta',
            field=models.TextField(blank=True, null=True, verbose_name='Technical information for the draw'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='number_of_players_in_team_max',
            field=models.IntegerField(default=1, verbose_name='Number of players per team (including substitutes)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='number_of_players_in_team_min',
            field=models.IntegerField(default=1, verbose_name='Minimum number of players per team'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='place',
            field=models.CharField(max_length=500, verbose_name='Venue'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='power',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Tournament power'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rating_coefficient',
            field=models.FloatField(default=1, verbose_name='Rating coefficient'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='teams_limit',
            field=models.IntegerField(default=100, verbose_name='Team limit'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='terms',
            field=models.FileField(blank=True, null=True, storage=federation.storage.MediaStorage(), upload_to='', verbose_name='Regulations'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='total_number_of_teams',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total number of teams'),
        ),
    ]
