# Generated by Django 5.1.6

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0071_alter_arbitertournamentmembership_is_main_arbiter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_date',
            field=models.DateField(blank=True, help_text='Publication or issue date of the document', null=True, verbose_name='Document date'),
        ),
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='document',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Download count'),
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-document_date', '-created_at'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документи'},
        ),
    ]
