# Generated by Django 5.1.6 on 2026-07-02 14:58

import django.core.validators
import federation.storage
import federation.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0072_add_document_date_and_download_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=federation.storage.MediaStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), federation.validators.validate_image_file_size, federation.validators.validate_image_dimensions, federation.validators.validate_image_format], verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=federation.storage.MediaStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), federation.validators.validate_image_file_size, federation.validators.validate_image_dimensions, federation.validators.validate_image_format], verbose_name='avatar'),
        ),
    ]
