# Generated by Django 5.1.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0073_alter_club_logo_alter_player_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='insurance_expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Insurance valid until'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='requires_insurance',
            field=models.BooleanField(default=False, verbose_name='Insurance required'),
        ),
    ]
