# Generated by Django 5.2.16 on 2026-07-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0074_player_insurance_tournament_requires_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='petanque_draw_id',
            field=models.TextField(blank=True, default='', verbose_name='Petanque draw ID'),
        ),
    ]
