# Generated by Django 5.2.16 on 2026-07-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0075_tournament_petanque_draw_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
