# Generated by Django 5.2.16 on 2026-08-05 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0076_club_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtournamentmembership',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_team_memberships', to='federation.player', verbose_name='Coach'),
        ),
    ]
