# Generated by Django 5.2.16 on 2026-08-05 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0077_teamtournamentmembership_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerTournamentMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('organizer', 'Organizer')], default='organizer', max_length=50, verbose_name='Role')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='federation.player', verbose_name='Організатор')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='federation.tournament', verbose_name='Турнір')),
            ],
            options={
                'verbose_name': 'Організатор турніру',
                'verbose_name_plural': 'Організатори турніру',
                'unique_together': {('tournament', 'organizer')},
            },
        ),
    ]
