[program:web-service]
command = /application/gunicorn_start                                 ; Command to start app
environment=LANG=en_US.UTF-8,LC_ALL=en_US.UTF-8                       ; Set UTF-8 as default encoding

[program:cron]
command=/usr/sbin/cron -f
autostart=true
autorestart=true
stderr_logfile=/var/log/cron_err.log
stdout_logfile=/var/log/cron_out.log