# the upstream component nginx needs to connect to
upstream django {
    server petanque_portal_web_api:8000; # stream using http server due to app is running in separate container
}

# configuration of the server
server {

    # the port your site will be served on, default_server indicates that this server block
    # is the block to use if no blocks match the server_name
    listen      8080 default_server;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        autoindex on;
    }

    # the domain name it will serve for
    # server_name .example.com; # substitute your machine's IP address or FQDN
    charset     utf-8;

    # max upload size
    client_max_body_size 1024M;   # adjust to taste

    # Static
    location /static/ {
        alias /application/static/;
        gzip_static on;
        expires max;
        add_header Cache-Control public;
    }

    # Static
    location /media/images/ {
        alias /application/media/images/;
        gzip_static on;
        expires max;
        add_header Cache-Control public;
    }

    # location / {
    #     return 301 https://$host$request_uri;
    # }

    # Finally, send all non-media requests to the Flask server.
    location / {
        proxy_pass  http://django;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
    }
}

server {
    listen 443 ssl;

    # max upload size
    client_max_body_size 1024M;   # adjust to taste
    charset     utf-8;

    #server_name portal.petanque.org.ua;

    ssl_certificate /etc/letsencrypt/live/portal.petanque.org.ua/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/portal.petanque.org.ua/privkey.pem;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options DENY always;
    add_header X-Content-Type-Options nosniff always;

    # Static
    location /static/ {
        alias /application/static/;
        gzip_static on;
        expires max;
        add_header Cache-Control public;
    }

    # Static
    location /media/images/ {
        alias /application/media/images/;
        gzip_static on;
        expires max;
        add_header Cache-Control public;
    }

    location / {
        proxy_pass http://django;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
    }
}
