"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os, json

def get_credential(name):
    try:
        credentials = json.loads(os.environ.get('APP_CREDENTIALS', '{}'))
    except:
        credentials = {}
        
    return credentials.get(name, None)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

GEOS_LIBRARY_PATH = '/usr/lib/libgeos_c.so.1'
#GDAL_LIBRARY_PATH = '/usr/lib/ogdi/libgdal.so'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k1n!-r2wazl!q#2dn3wa9_lm5v2))#n-k8veqn_u@+^0-@4m$w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_credential('debug')

ALLOWED_HOSTS = get_credential('domains')

CSRF_TRUSTED_ORIGINS = get_credential('domains')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'django_countries',
    'crispy_forms',
    'crispy_bootstrap5',
    'captcha',
    'federation',
    'dbbackup',
    'storages',
    'corsheaders',
    'silk',
]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': get_credential('db_name'),
        'USER': get_credential('db_user'),
        'HOST': get_credential('db_host'),
        'PASSWORD': get_credential('db_pass'),
        'PORT': get_credential('db_port'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = get_credential('language')
CURRENT_COUNTRY = get_credential('country')

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

CRISPY_ALLOWED_TEMPLATE_PACKS = ("bootstrap3", "bootstrap4", "bootstrap5")
CRISPY_TEMPLATE_PACK = "bootstrap5"


CONTENT_TYPES = ['image']

# 2.5MB - 2621440
# 5MB - 5242880
# 10MB - 10485760
# 20MB - 20971520
# 50MB - 5242880
# 100MB 104857600
# 250MB - 214958080
# 500MB - 429916160
MAX_UPLOAD_SIZE = "2621440"

# Static files storage in S3
AWS_STORAGE_BUCKET_NAME = get_credential('s3_bucket')
AWS_S3_REGION_NAME = get_credential('s3_region')  # e.g. us-east-2
AWS_ACCESS_KEY_ID = get_credential('s3_key')
AWS_SECRET_ACCESS_KEY = get_credential('s3_secret')

# Tell django-storages the domain to use to refer to static files.
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
AWS_S3_ENDPOINT_URL = "https://s3.%s.amazonaws.com" % AWS_S3_REGION_NAME

DBBACKUP_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
DBBACKUP_STORAGE_OPTIONS = {
    'access_key': get_credential('s3_key'),
    'secret_key': get_credential('s3_secret'),
    'bucket_name': get_credential('s3_bucket'),
    'region_name': AWS_S3_REGION_NAME,
    'location': get_credential('s3_backups_folder'),
    'endpoint_url': AWS_S3_ENDPOINT_URL,
}

DBBACKUP_CONNECTOR_MAPPING = {
    'postgresql': 'dbbackup.db.postgresql.PgDumpConnector',
    'django.db.backends.postgresql': 'dbbackup.db.postgresql.PgDumpConnector'
}


# Tell the staticfiles app to use S3Boto3 storage when writing the collected static files (when
# you run `collectstatic`).
AWS_S3_OBJECT_PARAMETERS = {
    'Expires': 'Thu, 31 Dec 2099 20:00:00 GMT',
    'CacheControl': 'max-age=94608000',
}

STATICFILES_LOCATION = 'static'
STATICFILES_STORAGE = 'federation.storage.StaticStorage'
STATIC_URL = '//'+AWS_S3_CUSTOM_DOMAIN+'/'+STATICFILES_LOCATION+'/'
STATIC_ROOT = STATIC_URL

MEDIAFILES_LOCATION = 'media'
DEFAULT_FILE_STORAGE = 'federation.storage.MediaStorage'
MEDIA_ROOT = '//'+AWS_S3_CUSTOM_DOMAIN+'/'+MEDIAFILES_LOCATION+'/'
MEDIA_URL = MEDIA_ROOT

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
MEDIA_RELATIVE_ROOT = 'images/'
MEDIA_BASE = os.path.join(BASE_DIR, 'media/')

MEDIA_FILES_PATH = os.path.join(BASE_DIR, 'media/images/')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static/"),
    MEDIA_ROOT,
]

DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800 # 50Mb

RECAPTCHA_PUBLIC_KEY = get_credential('recaptcha_public_key')
RECAPTCHA_PRIVATE_KEY = get_credential('recaptcha_private_key')
NOCAPTCHA = True

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240


CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_METHODS = [
    'GET'
]