FROM python:3.11-bookworm
ENV PYTHONUNBUFFERED 1

# Install software
RUN apt-get update && apt-get install -y wget gnupg2
RUN echo "deb http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list
RUN wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | tee /etc/apt/trusted.gpg.d/postgresql.asc

RUN apt-get update -y && apt-get install -y supervisor postgresql-client-17 cron gettext


# Install pinned requirements from the lockfile (gunicorn included)
ADD ./application/requirements.txt /application/requirements.txt
ADD ./application/requirements.lock /application/requirements.lock
RUN pip install -r /application/requirements.lock

# Copy server configurations
ADD ./conf/ /conf/

# setup all the configfiles
RUN ln -s /conf/supervisor-app.conf /etc/supervisor/conf.d/
COPY /conf/crontab.txt /etc/cron.d/portal_cron

# Copy application files into container
ADD ./application /application/

# Make launch script executable
RUN chmod 777 /application//gunicorn_start

WORKDIR /application/

# Run application
ENTRYPOINT ["supervisord", "-n"]
# CMD gunicorn api.wsgi:application --bind "0.0.0.0:8000" --workers 3 --reload --name api
