FROM nginx

USER root

# Copy application files into container
ADD ./application/static/ /application/static/

# RUN rm /etc/nginx/conf.d/default.conf
ADD ./conf/web-service-server.conf /etc/nginx/conf.d/

EXPOSE 8080